[tmdb]
language = "en-US"
watch_region = "AT"
poster_size = "w500"
max_posters_per_media = 1

[watch_providers]
access_types = ["flatrate", "rent", "buy"]
subscribed_flatrate_provider_names = ["Netflix", "Amazon Prime Video", "Apple TV", "Disney Plus"]
