"""Public data-access API for the media catalog and user library."""

from .catalog import (
    add_media,
    delete_media,
    insert_missing_series_season_posters,
    poster_filename_is_referenced,
    replace_media_posters,
    replace_media_watch_providers,
    save_media_catalog_draft,
    save_media_draft,
    update_media_tmdb_posters_checked_at,
    update_media_tmdb_watch_providers_checked_at,
)
from .errors import ConcurrentEditError, MetadataRefreshConflict
from .queries import (
    get_db_actors,
    get_db_creators,
    get_db_directors,
    get_db_episode_details,
    get_db_genres,
    get_db_media_metadata,
    get_db_media_posters,
    get_direct_media_posters,
    get_db_media_watch_providers,
    get_db_origin_language,
    get_db_production_companies,
    get_db_production_countries,
    get_db_series_episode_watch_history,
    get_db_series_episodes,
    get_db_series_summary,
    get_db_series_view,
    get_db_spoken_languages,
    get_db_writers,
    get_media_by_id,
    get_media_by_imdb_id,
    get_media_by_tmdb_id,
)
from .refresh import apply_metadata_refresh
from .user_data import (
    apply_media_state_patch,
    apply_media_user_changes,
    create_list,
    delete_list,
    get_all_lists,
    get_db_media_user_data,
    get_empty_media_user_data,
    get_media_state,
    set_media_watch_state,
    sync_series_episode_watch_history,
    update_list,
)


__all__ = [
    "ConcurrentEditError",
    "MetadataRefreshConflict",
    "add_media",
    "apply_media_state_patch",
    "apply_media_user_changes",
    "apply_metadata_refresh",
    "create_list",
    "delete_list",
    "delete_media",
    "get_all_lists",
    "get_db_actors",
    "get_db_creators",
    "get_db_directors",
    "get_db_episode_details",
    "get_db_genres",
    "get_db_media_metadata",
    "get_db_media_posters",
    "get_direct_media_posters",
    "get_db_media_user_data",
    "get_db_media_watch_providers",
    "get_db_origin_language",
    "get_db_production_companies",
    "get_db_production_countries",
    "get_db_series_episode_watch_history",
    "get_db_series_episodes",
    "get_db_series_summary",
    "get_db_series_view",
    "get_db_spoken_languages",
    "get_db_writers",
    "get_empty_media_user_data",
    "get_media_by_id",
    "get_media_by_imdb_id",
    "get_media_by_tmdb_id",
    "get_media_state",
    "insert_missing_series_season_posters",
    "poster_filename_is_referenced",
    "replace_media_posters",
    "replace_media_watch_providers",
    "save_media_catalog_draft",
    "save_media_draft",
    "set_media_watch_state",
    "sync_series_episode_watch_history",
    "update_list",
    "update_media_tmdb_posters_checked_at",
    "update_media_tmdb_watch_providers_checked_at",
]
