from app.paths import ICONS_DIR, MEDIA_POSTERS_DIR


DETAIL_ICON_DIR = ICONS_DIR / "media_details"
WATCH_HISTORY_ICON_DIR = ICONS_DIR / "watch_history"
POSTER_DIR = MEDIA_POSTERS_DIR

DETAIL_ICON_BUTTON_SIZE = 20
DETAIL_ICON_SIZE = 18
DETAIL_BUTTON_WIDTH = 100
DETAILS_BACKGROUND_COLOR = "#f1f1f1"

WATCH_ENTRY_DATE_INPUT_WIDTH = 140
WATCH_ENTRY_EPISODE_BUTTON_WIDTH = 28
WATCH_ENTRY_EPISODE_BUTTON_HEIGHT = 24
WATCH_ENTRY_EPISODE_BUTTON_BORDER_RADIUS = 7
WATCH_ENTRY_EPISODE_BUTTON_FONT_SIZE = 11
WATCH_ENTRY_EPISODE_BUTTON_SELECTED_COLOR = "#8fc4ff"
WATCH_ENTRY_EPISODE_BUTTON_WATCHED_COLOR = "#d0d0d0"
WATCH_ENTRY_EPISODE_BUTTON_SPACING = 4
WATCH_ENTRY_HEADER_TO_EPISODES_SPACING = 12
WATCH_ENTRY_HEADER_TO_BUTTONS_SPACING = 12
WATCH_ENTRY_EPISODES_TO_BUTTONS_SPACING = 12
WATCH_ENTRY_SEASON_ROW_SPACING = 4
